services:
  - type: web
    name: blog-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog_project.blog_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_project.settings
